### ISSUE TITLE
Shuffle_particles is moving floppy bodies even if they aren't supposed to move

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#104]
In the imp tutorial you can see, it's moving those little guys all over the place, even for the particles in subunits that don't have any movers.

edit: I mean representation::shuffle_configuration()

**Comment by cgreenberg** [comment]
The problem is that BuildModel is automatically adding all the beads it creates to the floppy body list. But we want to explicitly define what is moved.

**Comment by Pellarin** [comment]
If I understood correctly what you say, this behaviour is OK. Floppy bodies are generated for all missing parts. Therefore their initial position is arbitrary, also for fixed subunits. They need to be optimized, therefore we also randomize their initial coordinates.

**Comment by cgreenberg** [comment]
Ah ok. It makes sense. Though in some cases the user might want to only sample a part of the system, and ignore missing regions for fixed components.
