### ISSUE TITLE
RMF output from modeling with crosslinks not displaying as expected in Chimera

### ISSUE THREAD

**Issue by bifxcore** [salilab/pmi#108]
I am attempting to build a protein complex using experimental cross-links as input to modeling.py, modified from the rnapolii example.

When I load the modeling.rmf output into chimera and plot all constraints for one component, the legend only shows the name of the last constraint (see picture) instead of listing every selected constraint. Not sure if this is an issue for IMP or Chimera. Using Chimera 1.10.1 on MacOS 10.8.5

The output from modeling.py shows expected ISDCrossLinkMS data.

![constraints_plot](https://cloud.githubusercontent.com/assets/6655228/5969437/b632f808-a7d8-11e4-8b64-5ff63f62a6c1.png)

Isabelle

**Comment by Pellarin** [comment]
Hi! I think that is a Chimera-related issue. Using chimera to display the cross-link time-series is not a great idea. You can use an external plot software to display the distances using `imp/module/pmi/pyext/src/process_output.py` to extract the information from the stat file. see `http://integrativemodeling.org/nightly/doc/tutorial/rnapolii_3.html`

**Comment by bifxcore** [comment]
Thanks Riccardo, the tutorial is very helpful!
