### ISSUE TITLE
Update to use new IMP::atom::Representation

### ISSUE THREAD

**Issue by drussel** [salilab/pmi#11]
See https://github.com/salilab/imp/blob/feature/multiresolution/modules/atom/examples/multiresolution.py for an example. If the different resolutions are linked using this decorator then they will be written out to RMFs with better structure and a normal IMP::atom::Selection can be used with them.

**Comment by Pellarin** [comment]
Currently add_component_pdb(resolutions=[0,1,10])

```
-> 

root_node -> 
                 -> component_name
                                                   Fragment 1-100: ->
                                                                                  Res:0
                                                                                                  Residue 1
                                                                                                                  Atom1

                                                                                  Res:1 -> 
                                                                                                  Fragment 1-1
                                                                                  Res:10 -> 
                                                                                                  Fragment 1-10

```

This will be the scheme:

```
root_node -> 
                 -> component_name
                                                   Fragment 1-100: ->
                                                                                  Res:0
                                                                                                  Residue 1
                                                                                                                  Atom1
```

Where Fragment 1-100: will decorated by Representation

**Comment by Pellarin** [comment]
We have to change 
IMP.pmi.Representation.add_component_pdb 
IMP.pmi.Representation.coarse_hiearchy
IMP.tools.select

**Comment by Pellarin** [comment]
Steps 
1. use atom.Representation atom.Selection instead of the above functionality
2. remove no longer needed caches and markup
3. think about directly using eg atom.Selection instead of calling pmi function

**Comment by Pellarin** [comment]
test_selection tests whether the new selection returns the same old results.
test_hierachy_construction fails if the hierachy does not construct
test_restraints test whether all restraints defined in pmi have the same score
system specific tests (such as loop_reconstruction) I'll add other tests
