### ISSUE TITLE
A memory issue for clustering of ~1000 good scoring models

### ISSUE THREAD

**Issue by procyon777** [salilab/pmi#111]
There is a memory issue for clustering of ~1000 good scoring models for Nup82.  Whenever I specify the number of clusters under 5 (especially 1 or 2), the clustering job (IMP.pmi.macros.AnalysisReplicaExchange0.clustering) dies while "getting coordinates for frame ### rmf file".

Initially the clustering job successfully generated "distance.rawmatrix.pkl.data", "distance.rawmatrix.pk.npy", and ".macro.pkl" files.  Then the clustering job failed at random rmfs, while reading coordinates of the rmf frames and writing to the "cluster.X" folder.  I repeated multiple times and the job still died at random rmfs.

If I reduce the total number of rmfs to 500 or less, the issue is no longer detected (or possibly much lower chance of memory problem).  I'm using the recent IMP and PMI built on Feb 9th.

The scripts are available at
/netapp/sali/kimsj/NPC/nup82-master/Jackknifing/analysis_1-10_no_em/2_job_clustering_precision_rmsf_chef.sh

**Comment by cgreenberg** [comment]
Some ideas: 
--the final cluster writing (where it creates one RMF file for each cluster component) is done on a single CPU, we could split that up
-- it's probably silly to write potentially hundreds of RMF files, we could instead just write frames to a single file. On the other hand it's hard to do that in parallel.

**Comment by procyon777** [comment]
One thing I noticed too was, the writing of the rmf files (to the "cluster.X" folder) gets significantly slowed down with increasing number of rmf files.

For example, it takes just one minute to write 0.rmf3 ~ 50.rmf3.  However, it takes one minute to write 303.rmf3 ~ 305.rmf3.  So the writing rate dramatically drops 50 rmfs / minute to 3 rmfs / minute.  Why it is happening?  The clustering job eventually dies when the writing rate approaches to zero rmfs / minute.

**Comment by Pellarin** [comment]
Yes, I knew that. The problem is that each new rmf file is appended as a new hierarchy. That is memory-consuming. I tried to link the existing with a new rmf reading (that would be nicer with the memory), but it didn't work. I'll try to write a test function.

**Comment by Pellarin** [comment]
Latest commit 49cb3cd165039e5b905604ac9cb24469d0c0a72c should have fixed that. SJ can you check that now the analysis works nicely?

**Comment by Pellarin** [comment]
Can we close it?

**Comment by Pellarin** [comment]
SJ can you tell if this issue is still there? Thanks!

**Comment by procyon777** [comment]
I'll try it in a few days, with the new Nup82 models after EM restraint / filter.
I'm gonna let you know soon

**Comment by procyon777** [comment]
I can say now this issue was fixed.
