### ISSUE TITLE
topology should also allow single digit numbers for chain identifiers

### ISSUE THREAD

**Issue by petercim** [salilab/pmi#112]
If PDB Chain is a number (it happens when there's more than 25 chains in a PDB), IMP gets stuck with this error:

PDB Chain format for component  beta7 , line  20  is not correct
Correct syntax is a single uppercase letter. | 7 | was given.

Could someone fix this in the TopologyReader class (line 666)?

Thanks!

**Comment by saltzberg** [comment]
Try it now.  I'm having issues with my local IMP, so can't test it
immediately.

On Wed, Apr 8, 2015 at 2:30 PM, petercim notifications@github.com wrote:

> If PDB Chain is a number (it happens when there's more than 25 chains in a
> PDB), IMP gets stuck with this error:
> 
> PDB Chain format for component beta7 , line 20 is not correct
> Correct syntax is a single uppercase letter. | 7 | was given.
> 
> Could someone fix this in the TopologyReader class (line 666)?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/salilab/pmi/issues/112.

## 

Daniel Saltzberg
Post-doctoral Scholar
University of California at San Francisco
Lab of Andrej Sali (www.salilab.org)

T: 415.514.4258

_Mailing Address:_
UCSF MC 2552,
Mission Bay, Byers Hall
1700 4th Street, Suite 503B
San Francisco, CA 94158-2330

saltzberg@salilab.org
ds229@bu.edu

**Comment by Pellarin** [comment]
can we close this?

**Comment by benmwebb** [comment]
This seems to work fine in current PMI.
