### ISSUE TITLE
Problem of ambiguous XL restraints (sharing a same group ID), when applied to a same bead at coarse-grained representation

### ISSUE THREAD

**Issue by procyon777** [salilab/pmi#116]
I would like to report a PMI issue of the ambiguous XL restraints (sharing a same group ID), when applied to a same bead at coarse-grained representation.

  For example, there are 4 ambiguous XL restraints (DSS) defined for Nup82 616-621 as follows.

Nup82.1    616  -  Nup82.1    621    1    1289
Nup82.1    616  -  Nup82.2    621    1    1289
Nup82.2    616  -  Nup82.1    621    1    1289
Nup82.2    616  -  Nup82.2    621    1    1289

  These 4 XL restraints were grouped with an indentical group ID # 1289, and residues of 616 and 621 were coarse-grained together as a single bead (20 residues per bead).

  Because two residues of 616 and 621 were represented in a single same bead, the "IMP.pmi.restraints.crosslinking.ISDCrossLinkMS" automatically NEGLECTS the intra-molecular XLs of  "Nup82.1    616 -  Nup82.1    621 and  Nup82.2    616  -  Nup82.2    621".  Then only the inter-molecular XLs of "Nup82.2    616  -  Nup82.1    621 and Nup82.1    616  -  Nup82.2    621" were considered during the Monte Carlo steps, enforcing the inter-molecular XLs alone. 

  As a result, the ISD XL score reports the inter-molecular XLs only and these XLs were violated at most times.  In fact, this XL should not be violated because these two residues are close enough in a same intra-molecular Nup82 unit.  Also it tries to enforce two different Nup82 units come closer, which may be an artifact.

  Therefore I suggested not neglecting the intra-molecular XLs (sharing a same group ID), when applied to a same bead at coarse-grained representation.  But we must still keep neglecting the intra-molecular XLs for identical residues, such as (517:Nup82.1 - 517:Nup82.2).  Most importantly, it must apply only when the ambiguous XL restraints have the "SAME group ID".  If the group IDs are different, there should no change at all in the current PMI.

**Comment by procyon777** [comment]
A quick and dirty fix, in pmi/pyext/src/restraints/crosslinking.py
984:                if p1 == p2:
985:                    continue

-->  

984:               if (p1 == p2) and (r1 == r2):
985:                    continue

**Comment by Pellarin** [comment]
Yes, you're right, I fixed in the latest commit e0dbdc70f7e972d343a0c16b60dada7b558aec26
