### ISSUE TITLE
Score problem of ambiguous XL restraints, under the same unique (group) ID

### ISSUE THREAD

**Issue by procyon777** [salilab/pmi#117]
Whenever the multiple ambiguous XL restraints were applied under the same unique (group) ID, the "ISDCrossLinkMS_Data_Score_(...)" simply adds up all the scores in the same unique ID.  This generates unexpected higher weights for the specific set of the multiple ambiguous XL restraints under the same unique ID. 

For example,

If there are 4 ambiguous XLs under the same unique (group) ID, then the XL score is weighted 4 times than expected.

If there are 16 ambiguous XLs under the same unique (group) ID (this happens a lot for Nup82 complex), then the XL score is weighted 16 times.

This is not acceptable and we should keep only one score term for the total score.

**Comment by Pellarin** [comment]
Yes, I spot the problem and fixed that in the latest commit e0dbdc70f7e972d343a0c16b60dada7b558aec26

**Comment by Pellarin** [comment]
It is now tested in expensive_test_cross_link_ms_restraint.py

**Comment by Pellarin** [comment]
OK I assume this is closed!
