### ISSUE TITLE
allow creating molecule without a sequence

### ISSUE THREAD

**Issue by jkosinski** [salilab/pmi#118]
Now one cannot create a _Molecule object without a sequence, but this should be allowed.

Typical scenario is when a user has PDB files and xlinks and wants to optimize that, without providing sequences to add missing residues.

Sequence can always be added from PDB, in add_structure.

**Comment by cgreenberg** [comment]
We can do this, only complication is if we allow incomplete sequences then we have to create unstructured poly-A segments for the missing pieces. At least, we have to do that to avoid changing lots of code. I think that should be fine for allowing "quick" modeling.
