### ISSUE TITLE
Topology: create representation groups

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#128]
The current representation system is a little clunky. You tag residues with certain resolution numbers and then build() breaks the molecule into fragments based on common sets of resolutions. This is difficult to work with if the user has their own ideas about how to break up the sequence. In particular, we want to support non-linear representation groups like in "U" shaped proteins, e.g. this crappy diagram:

```
---100:150-------
                |
              50:100
---1:50---------|
```

The user may want to make two representation groups: (1-40,110-150) and (41-109). These groups may have volumetric representation (like Gaussians) as well as beads. This is difficult in the current scheme. Easier would be a create_representation() function and PMI::Representation class (although a better name might be "represented"):

``` python
state = s.create_state()
seqs = IMP.pmi.topology.Sequences('seqs.fasta')
mol = state.create_molecule("Prot1",sequence=seqs["Protein_1"])
mol.add_structure("prot1.pdb")
rep1 = state.create_representation(mol[1:40]+mol[110:150])
rep1.add_beads(structured_resolutions=[0,1,10],unstructured_resolution=10)
rep1.add_densities(residues_per_gaussian=12) 
```

A few notes:
- In principle this can allow representations that bridge molecules. This is potentially a problem due to the tree structure of the hierarchy. A fix would be to just disallow this until we come up with a better hierarchy structure.
- We'd need checks to make sure you don't create multiple Representations for the same residues.
- Could add option to make beads by averaging along backbone OR volumetric representation.

Thoughts?

**Comment by cgreenberg** [comment]
Volumetric representations now supported in PMI2.

**Comment by Pellarin** [comment]
I always think that PMI should provide one quick solution, and not all solutions, to a user problem. For all solutions, we have IMP.
