### ISSUE TITLE
Setting up a "WEIGHT" in the ISDCrossLinkMS class

### ISSUE THREAD

**Issue by procyon777** [salilab/pmi#134]
I just realized that the ISDCrossLinkMS class (in crosslinking.py) currently does not support the "set_weight" function.  Is there any specific reason not doing it?  I would like to play with the weight of the cross-link restraints with respect to other restraints.

Other classes (such as SimplifiedCrossLinkMS and SigmoidalCrossLinkMS) support the "set_weight" function, so it should be quite easy to implement the set_weight function.

**Comment by procyon777** [comment]
The line number 981 of crosslinking.py:
lw = IMP.isd.LogWrapper(restraints,1.0)

I guess we can put the weight here, instead of 1.0, is that correct?

**Comment by Pellarin** [comment]
Yes, but in principle the weight should not change because it is a bayesian
restraint. I don't recommend to do so. Change instead psi to a lower value,
that will do the same thing, but it has a meaning

# Riccardo Pellarin

Institut Pasteur
25, rue du Docteur Roux
75724 Paris Cedex 15, France
riccardo.pellarin@pasteur.fr
+33 1 40 61 34 75

**Comment by procyon777** [comment]
Thanks, do you mean the psi value below?

```
xl4.set_psi_is_sampled(False)
psi1 = xl4.get_psi(1.0)[0]
psi1.set_scale(0.05)
```

So should I change 1.0 in get_psi(1.0)[0] to some lower values?  A lower psi means a higher weight for the cross-link restraint?  Or the opposite?  I'm wondering what is going to be a reasonable range of the psi value.  Maybe I need to play with it

SJ

**Comment by Pellarin** [comment]
Yes, lower psi "almost" means higher weight. The slope part is the same
though.

# Riccardo Pellarin

Institut Pasteur
25, rue du Docteur Roux
75724 Paris Cedex 15, France
riccardo.pellarin@pasteur.fr
+33 1 40 61 34 75

**Comment by procyon777** [comment]
Whenever I try any lower values (0.1 ~ 0.5) instead 1.0 in get_psi(1.0)[0], then I suddenly get a significantly high score term in stat.out.

ISDCrossLinkMS_PriorPsi_Score 49922.xxxxx

It used to be ISDCrossLinkMS_PriorPsi_Score -2.99573227355 with the default setting of 1.0.

Also I have two score terms like below (using 0.5), one of which seems to be redundant 

ISDCrossLinkMS_Psi_0.5
ISDCrossLinkMS_Psi_1.0

Is that a bug?  The ISDCrossLinkMS_PriorPsi_Score can not be that high?

**Comment by Pellarin** [comment]
Sorry I haven't understand the issue. Can you write the code and the score values?
