### ISSUE TITLE
Problems and solutions for add_representation in Topology (PMI2)

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#141]
Here is how representation currently works in PMI::Topology: When you call mol.add_representation(atomic_res), the residues are "tagged" with resolutions (0,1,10,...). Later when you call PMI::Topology::Molecule::build(), it searches along the backbone and groups residues with identical lists of resolutions. Within each group, it calls IMP::atom::simplify_along_backbone() to make the beads.

Here are the current issues:
- no support for densities. These are volumetric representations, can be nonlinear in sequence and so aren't really compatible with the way PMI::Topology::Molecule::build() currently works. 
- of course, no support for dual representations - beads AND densities in the same sequence. this should now be possible with recent changes in IMP::atom::Representation()
- no support for ideal helices. that one is easy though.
- no support for custom boundaries for beads
- no support for representations that span multiple Molecules. I actually don't think this is a good idea, mainly because IMP can't really support it, as Representation relies on Fragments and those can only be associated with a single chain.

Solutions:
- Add new options to add_representation: 
  - For densities we'll add densities_per_residue, density_fn, and density_force_write. If you set these, once you call build() it'll call IMP::isd::gmm_tools::sample_and_fit_to_particles(). 
  - Another density option will be a flag, setup_particles_as_densities, which will set up each requested particle as a Gaussian. This is for all-atom or otherwise flexible beads where each bead is its own density.
  - ideal_helix flag
  - add_breakpoints
  - prevent calling add_representation() for a residue more than once.
- Changes to build(). Each call to add_representation() will store an internal representation unit. Within that we'll search for sequence breaks to setup backbone beads. Should make the code simpler. 

Also note that you'll be able to access the densities with IMP::atom::Selection(hier,representation_type=IMP.atom.DENSITIES).

**Comment by cgreenberg** [comment]
Volumetric representations, including densities, are now supported. There are a few remaining issues (RMF writing of density-decorated flexible beads, ideal helices) but we're mostly there. Example added in 5e0601a31d993bfafa53f5c350199af515eb0f01

**Comment by Pellarin** [comment]
> no support for densities. These are volumetric representations, can be nonlinear in sequence and so aren't really compatible with the way PMI::Topology::Molecule::build() currently works.

In principle a single gaussian of a GMM represents ALL residues (and not a set of residues) belonging to the domain/protein/complex represented by the GMM.
