### ISSUE TITLE
Accessing RB particle indexes from DOF class

### ISSUE THREAD

**Issue by saltzberg** [salilab/pmi#146]
I'm looking to access the components of rigid bodies through the PMI2 DOF class.  The class only stores the RigidBodyMover object (in the dof.movers list), from which I can't access them.  If I make the DOF object keep a list of RBs, this solves my problem.

The same issue exists for the assigned nonrigid members (which will be useful to know for the connectivity restraint...).

Charles, it looks like you had the beginnings of a particle mapping scheme.  Is that something you still think we should do?  Or am I missing some other way of doing this?

**Comment by cgreenberg** [comment]
Seems like a good idea. Then we could have `dof.get_rigid_parts()`, and `dof.get_flexible_parts()`.

But if you're going to be testing if a particle is part of a rigid body, say for your connectivity restraint, you can just use:

``` python
if IMP.core.RigidBodyMember.get_is_setup(p):
     rb = IMP.core.RigidBodyMember(p).get_rigid_body()
```

A few other things: `RigidBodyMember` is for ALL particles inside a rigid body. There's also `RigidMember` for the particles that are actually rigid, in contrast to `NonRigidMember`, which are the flexible beads within the rigid body that move along with it (you'll want to apply the connectivity restraint to them).

**Comment by cgreenberg** [comment]
Yeah having just looked over your restraint, it would be preferable not to pass the DOF object. Better to just check for rigid body status using IMP commands above.
