### ISSUE TITLE
multiscale.py fails when not in Test mode

### ISSUE THREAD

**Issue by saltzberg** [salilab/pmi#147]
In examples/multiscale.py, when testmode=False in the ReplicaExchange0 macro the following error comes up:

> Traceback (most recent call last):
>   File "multiscale.py", line 63, in <module>
>     rex.execute_macro()
>   File "/Users/saltzberg/salilab/imp_release/lib/IMP/pmi/macros.py", line 349, in execute_macro
>     output_hierarchies)
>   File "/Users/saltzberg/salilab/imp_release/lib/IMP/pmi/output.py", line 335, in init_rmf
>     IMP.rmf.add_hierarchies(rh, hierarchies)
>   File "/Users/saltzberg/salilab/imp_release/lib/IMP/rmf/**init**.py", line 756, in add_hierarchies
>     return _IMP_rmf.add_hierarchies(*args)
> RuntimeError: UsageError: "Collision on association keys."
> WARNING  No frames were saved to file "HierarchySaveLink0" even though objects were added.
> WARNING  Object "HierarchySaveLink0" was never used. See the IMP::Object documentation for an explanation.

**Comment by cgreenberg** [comment]
Yeah it goes away if you change `setup_particles_as_densities` to `False` (though that will be a problem if you want to restrain the flexible particles to an EM density map). The problem is RMF currently can't write particles that are also their own density representations. See salilab/imp#920

**Comment by saltzberg** [comment]
Cool.  Thanks.
