### ISSUE TITLE
Rigid body handling in PMI2

### ISSUE THREAD

**Issue by saltzberg** [salilab/pmi#149]
I've found some thing while building the ConnectivityRestraint and playing with the multiscale.py example that don't seem to work as expected.  I've included these in a bulky test (test_topology_multiscale.py) with 6086cd74052ed39529c55aed146ceed421972f13

So, starting from examples/multistate.py, a rigid body is created as:

``` python
dof.create_rigid_body(gcp2, nonrigid_parts=gcp2.get_non_atomic_residues())
```

which leads me to believe that the structured parts (581 residues) should be RigidMembers and the non-structured should be NonRigidMembers

If I get all leaves of the molecule, however:

``` python
all_things = IMP.atom.get_leaves(gcp2.get_hierarchy())
for h in all_things:
      print IMP.core.RigidMember.get_is_setup(h), IMP.core.NonRigidMember.get_is_setup(h)
```

I see that everything is a NonRigidMember (If I remove the nonrigid_parts=... from the dof.create_rigid_body(...), everything is now a RigidMember).  This is true for any list of hierarchies that I choose. 

So when running the multistate.py example as constructed through ConnectivityRestraint, the restraint is applied to all consecutive hierarchy pairs.  Is this what should be happening?  How would one then define different elements of the RigidBody to be RigidMembers and NonRigidMembers or is there another way to determine what is a mover and what is not (without the DOF class)?

**Comment by cgreenberg** [comment]
Looks like there was a sort of bug, basically TempResidue.get_has_structure() only worked if you had built res1 or res0. I'll change it to set a flag instead so that even if you remove the high res information it'll still remember it came from data.
Probably a good idea to figure out exactly the number of expected beads in an example system.
