### ISSUE TITLE
TempResidue get_residue_type() doesn't work

### ISSUE THREAD

**Issue by saltzberg** [salilab/pmi#150]
One can't print an instance of IMP.pmi.TempResidue, because the self.hier object is an IMP.atom.Hierarchy object, which does not have a get_residue_type() command, which causes problems with the get_code() and get_residue_type() functions.  Not sure how we would want to fix this.

A failing test is part of test_topology_multiscale.py 6086cd74052ed39529c55aed146ceed421972f13.

**Comment by cgreenberg** [comment]
Yeah it's tricky because after you build() sometimes the residues aren't there any more (like if you only have resolution 10). I'll change it to store the original type though.
