### ISSUE TITLE
Suggestion: change the name of pmi restraint class to contain Setup

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#154]
pmi.restraint is a module with classes that help the setup of restraints having complicated data. Should we call these classes SetupXXXX, for instance SetupElectronMicroscopyRestraint? That would make a difference from the real, IMP restraint without confusing the user.

**Comment by cgreenberg** [comment]
I don't know, I kinda like it as it is, mostly because adding Setup would make it much longer :) . I think as long as we link to the IMP restraint in the documentation and say it "wraps the XXX restraint..." it's probably fine.

**Comment by benmwebb** [comment]
I think the names are long enough already! And if you change all the names, you'd need to keep all the old ones anyway for a while (deprecated) to avoid breaking old code, which will be a mess.
