### ISSUE TITLE
Rename dof -> DegreesOfFreedom

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#155]
Bad to have abbreviations in major classnames.

**Comment by Pellarin** [comment]
I like it

**Comment by cgreenberg** [comment]
I guess would be annoying to do: 
`dof = IMP.pmi.DegreesOfFreedom.DegreesOfFreedom(mdl)`

Maybe instead we could merge the class into the `Samplers` namespace? Ugh.

**Comment by saltzberg** [comment]
Is there a way to have the object just be IMP.pmi.DegreesOfFreedom?
