### ISSUE TITLE
CrossLinkMSRestraint doesn't appear to support copy ambiguity

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#161]
I'm not exactly sure how that's supposed to work in PMI1, actually. @Pellarin how do you find all the copies of each particle? Looks like in the restraint you just call:

``` python
ps1 = IMP.pmi.tools.select(r,
                           resolution=resolution,
                           name=c1,
                           name_is_ambiguous=False,
                           residue=r1)
```

And just keep the first returned particle. Should you `set name_is_ambiguous = True` in order to get all the additional copies?

**Comment by Pellarin** [comment]
It is done manipulating the IMP.pmi.io.crosslink.CrossLinkDataBase object. See the example commited in 1f114cfe298bfac2ac737d7b27ca851281b43f6f
