### ISSUE TITLE
Shuffle sucks - sample instead?

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#165]
It won't work unless the rigid parts are already separated. Better idea would be to just simulate for a while  with only stereochemistry as the restraint. An easy solution would be to add a new macro (or add an option to replica exchange) to just disable all restraints but EVSphere and just run monte carlo for a while.

**Comment by Pellarin** [comment]
I disagree. Monte Carlo perturbation cannot guarantee a totally random initial conformation, where you've lost memory of the initial conformation. In other words, nobody can tell you how many MC steps are needed. We need to randomize the coordinates in the way we are currently doing, randomly displacing and rotating rigid bodies and beads.

**Comment by Pellarin** [comment]
What is the problem of having rigid bodies already initialized?

**Comment by cgreenberg** [comment]
I agree that shuffling randomly is more accurate. It's more for testing, really. When you already have the correct configuration, and all the rigid bodies are stuck together, the shuffle routine can't pull them apart.

**Comment by Pellarin** [comment]
OK, you mean it cannot pertub it when they're stuck together, because indeed it can tear it apart!

**Comment by cgreenberg** [comment]
Now that I think about it probably the simplest option is to have a "first_separate" flag that if True, moves each rigid body away from the center of mass, then shuffles as usual.

**Comment by benmwebb** [comment]
A distinct "separate" function would be cleaner.

**Comment by Pellarin** [comment]
I don't understand. The present function should work fine also if the system is initially packed. The only case where it could not work is when you're trying to randomize the system coordinated into a box too small. Can you provide an example of the behaviour you're mentioning?

**Comment by cgreenberg** [comment]
Maybe I'm using it incorrectly (or adapted it incorrectly with PMI2). I couldn't get it to work with RNAPOLII (1WCM.pdb). Seems to keep getting caught and not accepting any transformations.

**Comment by Pellarin** [comment]
are you using max_translation=300.? the default value? It should be large enough to arrange the system parts easily

**Comment by saltzberg** [comment]
I've had the same issues, even setting max_translation to 1000 or 10000.
It runs very fast, though, so maybe there is a bug?

**Comment by cgreenberg** [comment]
Seems to work ok now for RNAPOLII, at least in the mulitscale.py example

**Comment by cgreenberg** [comment]
I think we have things working...
