### ISSUE TITLE
Remove Biopython dependency?

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#170]
Maybe we can get rid of biopython, since it is only used to read Fasta sequences

**Comment by cgreenberg** [comment]
agreed, we just have to write a fasta reader (or can we use modeller?)

**Comment by benmwebb** [comment]
A FASTA reader is really easy to write. There's one in ModPipe in Python, for example, which would be easy to pull into IMP. You don't want the Modeller FASTA reader though - it's in Fortran!

BTW, `xltable.py` also uses `PDBParser` from biopython.

**Comment by cgreenberg** [comment]
You mean we can just copy the one from ModPipe, right? Can you point me towards it?

**Comment by benmwebb** [comment]
Sure, you can just copy it, since I wrote it. See the `FASTAFile` and `Sequence` classes in `/netapp/sali/ModPipe/SVN/lib/python/modpipe/sequence.py`. Once you trim out the ModPipe-specific stuff, the actual FASTA reader is pretty simple.
