### ISSUE TITLE
pmi.dof.input_adaptor() fails when passed a State

### ISSUE THREAD

**Issue by sethaxen** [salilab/pmi#171]
State.get_molecules() returns a dict matching molecule names to molecules. The input_adaptor tries to loop through this dict assuming it's looping through molecules, but it's just looping through the keys, so it fails when requesting a residue index.
See https://github.com/salilab/pmi/blob/develop/pyext/src/tools.py#L1427-L1430

**Comment by cgreenberg** [comment]
oops! will fix now.
