### ISSUE TITLE
Add option to pass geometries to ReplicaExchange0 which are added to the RMF file

### ISSUE THREAD

**Issue by sethaxen** [salilab/pmi#172]
I have some geometries which I've been adding to rmf files for easy visualization. I'd like to be able to use these with PMI. I'm imagining a geometries=[] option to ReplicaExchange0, and when the RMF file is opened, those geometries are added with IMP.rmf.add_geometries. And that's it (their orientations are updated by a constraint).

**Comment by benmwebb** [comment]
Please, no more constructor arguments! There's way too many already. Add a method instead.

**Comment by sethaxen** [comment]
If no one has any objections to adding a ReplicaExchange0.add_geometries() method which adds geometries to the stores self.vars and modifying Output.init_rmf() to take a geometries parameter, I can commit this code.

**Comment by cgreenberg** [comment]
sounds great!

**Comment by cgreenberg** [comment]
just be sure to add a test! even better, an example!

**Comment by saltzberg** [comment]
Currently, all movers are passed to ReplicaExchange via the DOF object.  Is
it straightforward to pass the geometry object to DOF and then have DOF
pass the movers along to ReplicaExchange?

The output for the RMF can be passed separately (like we do for
crosslinking).

On Tue, Feb 16, 2016 at 4:31 PM, Charles Greenberg <notifications@github.com

> wrote:
> 
> just be sure to add a test! even better, an example!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/salilab/pmi/issues/172#issuecomment-184940904.

## 

Daniel Saltzberg
Post-doctoral Scholar
University of California at San Francisco
Lab of Andrej Sali (www.salilab.org)

T: 415.514.4258

_Mailing Address:_
UCSF MC 2552,
Mission Bay, Byers Hall
1700 4th Street, Suite 503B
San Francisco, CA 94158-2330

saltzberg@salilab.org
ds229@bu.edu

**Comment by sethaxen** [comment]
That's not precisely correct. DOF maintains an internal list of movers, but the user actually requests that list of movers themselves and passes it to ReplicaExchange0 manually. It's trivial to store a list of geometries within DOF, but since DOF itself wouldn't generate them or use them and the user would need to add them to DOF and then re-request that stored list to pass to ReplicaExchange0.add_geometries(), it seems this just adds complication for no reason. Or am I missing something?

A geometry just holds other geometries and/or primitives. Once a geometry is created and passed to the RMF, the internal geometries/primitives can be updated anytime without needing to re-pass the geometry to the RMF; they'll update naturally. The constraint that ensures the geometry is updated is added to the model when created and never exposed to the user, so it wouldn't be stored by DOF.
