### ISSUE TITLE
ReplicaExchange0.execute_macro() fails with multiple states

### ISSUE THREAD

**Issue by sethaxen** [salilab/pmi#174]
When a single state is provided, the root hierarchy is stored in self.root_hier. When multiple states are provided, self.root_hier is not set (self.root_hiers is). However, at [line 295](https://github.com/salilab/pmi/blob/develop/pyext/src/macros.py#L295), it checks if self.root_hier is None, which results in the following error when multiple states are provided:

```
AttributeError: 'ReplicaExchange0' object has no attribute 'root_hier'
```

**Comment by cgreenberg** [comment]
Sounds like you're mixing PMI1 (the `representation` object) and PMI2. The `root_hier` object is only for PMI2, in which case the states are children of `root_hier`.

**Comment by cgreenberg** [comment]
OHHH sorry. I see what you're saying. It's doing something it shouldn't....

**Comment by cgreenberg** [comment]
Thanks for finding this! Easy fix.
