### ISSUE TITLE
autobuild_model complains that last residue is "not represented"

### ISSUE THREAD

**Issue by benmwebb** [salilab/pmi#182]
e.g. with latest IMP nightly build (PMI a16cc3c), running the Nup84 biological system:

```
$ python nup84.isd.modeling.py --test
...
               Nup84     724        Nup84_724_pdb     1.0    Nup84_715_724_pdb    10.0
               Nup84     725        Nup84_725_pdb     1.0    Nup84_725_726_pdb    10.0
               Nup84     726        Nup84_726_pdb     1.0    Nup84_725_726_pdb    10.0
               Nup84                  727 **** not represented ****
```

It complains similarly for each subunit in the complex. Nup84 has 726 residues, so it shouldn't be trying to look for residue 727 in the first place...

**Comment by cgreenberg** [comment]
Looks like the problem is our switch to the new sequence file reader. The nup84 sequence file is PIR formatted so it has an asterisk at the end. I...guess it's ok to just strip out any asterisks.

**Comment by cgreenberg** [comment]
Actually these nup84 files ARE fasta formatted (not PIR) they just have an asterisk at the end for some reason.
