### ISSUE TITLE
PMI2 DOF show 

### ISSUE THREAD

**Issue by shruthivis** [salilab/pmi#185]
IMP.pmi.dof.DegreesOfFreedom.show  no longer exists and should be removed from the documentation?

Maybe nice to add a function that user can see to track their progress in building DOF (just like IMP.atom.show_with_representations does for representations).

**Comment by cgreenberg** [comment]
Where do you see "show" in the documentation?
We have a very basic **repr** function, so if you `print dof_objc` it just prints all the movers. Agreed, though, we should have something nicer like:

```
- rigid body "name"
  - All parts
    - Mol1.1-100
  - Nonrigid parts
    - Mol1.25-75
```

Of course this could only print nicely if you set up with PMI objects

**Comment by shruthivis** [comment]
Got it thanks. Was looking at the wrong documentation (2.5 stable release)
:)

On Fri, Mar 11, 2016 at 3:35 PM, Charles Greenberg <notifications@github.com

**Comment by cgreenberg** [comment]
Let's leave it open as a reminder :)
