### ISSUE TITLE
Selection (for PMI restraints) should smartly divide low-res beads

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#188]
We have an annoying problem when you slice molecules for DOF or restraints: resX (where X>1) beads may appear more than once, for example:

``` python
dof.create_rigid_body(mol[0:15])
dof.create_rigid_body(mol[15:30])
```

If resolution 1 and 10 are both created for this molecule, there will be an error, because the res10 bead corresponding to residues 10-19 appears in both these selections (which are done internally in `input_adaptor`:

``` python
sel1 = IMP.atom.Selection(hier, residue_indexes=range(1,16), resolution=IMP.atom.ALL_RESOLUTIONS)
sel2 = IMP.atom.Selection(hier, residue_indexes=range(16,30), resolution=IMP.atom.ALL_RESOLUTIONS)
```

I'm not sure how this was avoided in PMI1. One solution is to have an additional filtering step in `input_adaptor` where we remove any `Fragments` (==resX beads) that don't have at least half the residues also ~~selected~~ requested. That way in the above rigid bodies, the res10 bead would only be in the first rigid body.

**Comment by cgreenberg** [comment]
OK, well, this is silly, because the problem is solved by adding hard breaks in the structure during add_representation: the `bead_extra_breaks` argument adds resX breaks in addition to the ones added at borders between structure and bead.

**Comment by saltzberg** [comment]
So does this mean that one must implement these breaks correctly, otherwise
you will run into the issue?

If so, we can maybe throw a warning if one selects a "partial" particle and
include this issue in the documentation for bead_extra_breaks

On Wed, Mar 16, 2016 at 3:28 PM, Charles Greenberg <notifications@github.com

> wrote:
> 
> OK, well, this is silly, because the problem is solved by adding hard
> breaks in the structure during add_representation: the bead_extra_breaks
> argument adds resX breaks in addition to the ones added at borders between
> structure and not-structure.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/salilab/pmi/issues/188#issuecomment-197585436

## 

Daniel Saltzberg
Post-doctoral Scholar
University of California at San Francisco
Lab of Andrej Sali (www.salilab.org)

T: 415.514.4258

_Mailing Address:_
UCSF MC 2552,
Mission Bay, Byers Hall
1700 4th Street, Suite 503B
San Francisco, CA 94158-2330

saltzberg@salilab.org
ds229@bu.edu

**Comment by Pellarin** [comment]
In pmi1 the common bead is split in two. I think we should do the same for pmi2

**Comment by cgreenberg** [comment]
After some discussion, it seems like the best solution is to raise an error if the user passes a slice like `mol[a:b]` when one of the ends is in the middle of a bead (like b=74 and there's a res10 bead that includes residues 70 to 79). PMI2 will already divide such a bead into two if 1) there's a structure segment that starts/ends at residue b or 2) the user passes b to `bead_extra_breaks` in `molecule.add_representation()`. We could just have `input_adaptor` raise an error if there is no break at b, and suggest a fix like putting b in `bead_extra_breaks`.
