### ISSUE TITLE
again issues with ClosePairContainer

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#19]
I have the following strange behaviour.

If I use my excluded volume term in this way:

```
ssps=IMP.core.SoftSpherePairScore(self.kappa)
lsa = IMP.container.ListSingletonContainer(self.m)
lsa.add_particles(particles) 
rbcpf=IMP.core.RigidClosePairsFinder()        
self.cpc=IMP.container.ClosePairContainer(lsa,0.0,rbcpf,10.0)
evr=IMP.container.PairsRestraint(ssps,self.cpc)
```

During the simulation, it looks like the excluded volume is not considered: everything collapses (due to other restraints)

If I remove `rbcpf` from `ClosePairContainer`, namely

```
self.cpc=IMP.container.ClosePairContainer(lsa,0.0,rbcpf,10.0)
->
self.cpc=IMP.container.ClosePairContainer(lsa,0.0,10.0)
```

the excluded volume works, but now it considers also the intra-rigid body terms.....

**Comment by drussel** [comment]
What is the ev score of the collapsed conformation? Perhaps with a new restraint to prevent cache effects.

**Comment by Pellarin** [comment]
The collapsed conformation has a ev score of about 17.

I'll try to write a test later today.

**Comment by drussel** [comment]
I might have found a related bug...

On Thu, Feb 6, 2014 at 10:29 AM, Riccardo Pellarin <notifications@github.com
