### ISSUE TITLE
imp fails to build with newest pmi

### ISSUE THREAD

**Issue by shanot** [salilab/pmi#193]
I removed the modules/pmi directory from my imp tree and replaced it by the latest version cloned from github.
On a centos 5 linux machine, I get the following errors during the configuration:

```
CMake Error at modules/pmi/src/CMakeLists.txt:35 (include):
  include could not find load file:

    Files.cmake


CMake Error at modules/pmi/test/CMakeLists.txt:33 (include):
  include could not find load file:

    Files.cmake


CMake Error at modules/pmi/examples/CMakeLists.txt:28 (include):
  include could not find load file:

    Files.cmake


CMake Error at modules/pmi/benchmark/CMakeLists.txt:31 (include):
  include could not find load file:

    Files.cmake


CMake Error at modules/pmi/bin/CMakeLists.txt:31 (include):
  include could not find load file:

    Files.cmake


CMake Error at modules/pmi/utility/CMakeLists.txt:31 (include):
  include could not find load file:

    Files.cmake


Configuring module saxs_merge ...yes
-- Running setup_swig_wrappers saxs_merge
-- Running IMP.saxs_merge making all header
Configuring module EMageFit ...Required module IMP.em2d not available
Module IMP.EMageFit disabled
libTau not found
Configuring module cnmultifit ...Required dependency libTau not found
Module IMP.cnmultifit disabled
Configuring module integrative_docking ...Required module IMP.em2d not available
Module IMP.integrative_docking disabled
-- Running setup_swig_dependencies
-- Creating thread pool with 16 threads
-- Running setup_imppy
-- Documentation disabled as doxygen not found
-- Configuring incomplete, errors occurred!
See also "/work/sam/imp-fast/CMakeFiles/CMakeOutput.log".
ninja: error: rebuilding 'build.ninja': subcommand failed
```

CMakeOutput.log is attached (renamed as txt)

[CMakeOutput.txt](https://github.com/salilab/pmi/files/195439/CMakeOutput.txt)

Any ideas ? Thanks

**Comment by benmwebb** [comment]
I'm 99.999% certain this isn't due to any change in PMI, since only two lines of code have changed in PMI-develop relative to the code in IMP, and those two lines are in an example (802e636594). So you must have broken something else somewhere.

Those `Files.cmake` files are generated automatically when you run cmake (it in turn runs a script called `setup_cmake`). So possibly that failed for some reason - perhaps you don't have write permission to `modules/pmi`?

**Comment by shanot** [comment]
I have all the rights setup properly, and I am building exactly as I used
to - which worked before. I'll keep looking.

**Comment by shanot** [comment]
Well, looks like trying again a few days later fixed it.
