### ISSUE TITLE
What is the idea behind the numbering of residues in PMI2 ?

### ISSUE THREAD

**Issue by shanot** [salilab/pmi#194]
In particular, why passing an int to **getitem** in a pmi2 molecule means 0-ordered, and passing a string means 1-ordered ?

This leads to weird slicing behavior.

**Comment by benmwebb** [comment]
How else would it work? What is the "weird slicing behavior" you refer to?

**Comment by Pellarin** [comment]
pmi2.molecule[1:4]=OrderedSet(['res2','res3','res4'])

I know that it would break the pythonic architecture, but it would be much
more intuitive for the user if:

pmi2.molecule[1:4]=OrderedSet(['res1','res2','res3','res4'])

# Riccardo Pellarin, PhD

Institut Pasteur
CNRS UMR 3528
25, rue du Docteur Roux
75724 Paris Cedex 15, France
riccardo.pellarin@pasteur.fr
+33 (0)1 44 38 93 63

**Comment by benmwebb** [comment]
Not sure why you think that would be more intuitive, since Python ranges are always half open. I would certainly find the latter syntax horribly confusing. What's wrong with

```
pmi2.molecule[:4]=OrderedSet(['res1','res2','res3','res4'])
```

**Comment by Pellarin** [comment]
Well then we need another method to slice using residue indexes, because I find myself the current syntax horribly confusing, and prone to errors.

**Comment by cgreenberg** [comment]
You can also do mol.residue_range('5','10'). Riccardo, what's confusing exactly? I tried to copy the same syntax as modeller. We certainly should not try to change the behavior of python lists.

**Comment by Pellarin** [comment]
> mol.residue_range('5','10')

Ok I like that better, I overlooked it.

**Comment by Pellarin** [comment]
Anyways, if one forgets that these are python lists, from the point of view of a user, maybe not accustomed with data-structure details, I find confusing that  mol[3:10] returns from residue 4 to residue 10... Maybe I see things from the wrong perspective, and it it looks like we cannot do much.

 I like the residue_range method, but why it takes strings and not integers??

**Comment by cgreenberg** [comment]
Yeah, maybe we could change residue range to take numbers in PDB order.

**Comment by shanot** [comment]
What got me confused is that as a user I have to juggle with two conventions (if I got it right):
When adding a structure from a pdb, the range provided follows the pdb convention.
However, when slicing the range follows python list convention.

I think both are fine but having a unified behaviour would be less error prone, at least for dumbasses like me.

**Comment by cgreenberg** [comment]
Thanks for clarifying. Yeah, that is probably bad, but I don't know which standard to pick :) If we make it uniform PDB-style numbers then we have to do destroy normal python functionality, which is a no-go. A good move would be to use the same integers-are-0-ordered and strings-are-1-ordered standard for `add_structure`. A little ugly but it would be consistent.

**Comment by benmwebb** [comment]
PDB numbering is not guaranteed to be consistent in any way, so using it for slicing isn't a good idea. Numbers may not be contiguous, they may start at values other than 1, and may even be repeated (with insertion codes).

**Comment by shanot** [comment]
Perhaps using PDB_res_range instead of res_range in add_structure would
solve it ?
