### ISSUE TITLE
PMI2 hierarchy display in RMF

### ISSUE THREAD

**Issue by shruthivis** [salilab/pmi#199]
Not sure if this is an RMF issue or Chimera issue or PMI2 issue.
I'm trying to use [rmfalias](https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/midas/rmfalias.html) to create aliases for PMI2 hierarchies in Chimera (so I can easily select them on command line, color them etc) e.g. 
rmfalias
color red System/State_0/Spc97

But if there are multiple copies of a protein,all these appear with the same name at the same level in Chimera. And rmfalias selects only the last one, as mentioned in the doc linked above. Can we add copy number to the RMF for chimera display purposes so that the names in the hierarchy on a single level are unique?

**Comment by cgreenberg** [comment]
That would be a great idea, but I think this is a Chimera issue. You could file a bug report with them or email Conrad Huang in their lab. Unless @benmwebb you know how to change how Chimera identifies a molecule (e.g. would be cool to do `molname.copy_index.state_index`)

As a temporary solution you can actually control the color that each molecule (and each copy) is displayed by setting color options during setup in PMI2. In `molecule.add_representation()` you can pass `color=(R,G,B)` where R,G,B are values from 0 to 1.

**Comment by Pellarin** [comment]
Yes, I was wondering too. Maybe changing the Particle name only (and
keeping the same Hierarchy name)?

# Riccardo Pellarin, PhD

Institut Pasteur
CNRS UMR 3528
25, rue du Docteur Roux
75724 Paris Cedex 15, France
riccardo.pellarin@pasteur.fr
+33 (0)1 44 38 93 63

**Comment by shruthivis** [comment]
Ok will talk to Chimera people. Yes one could do it in IMP/PMI2 but it is a
bit of a pain to currently map the PMI RGBs to Chimera colors. :)
Didn't we say something will be done about PMI colors at some point?

**Comment by cgreenberg** [comment]
Probably a good idea to also just dump in all the Chimera color names so you could just pass names. I'll do that. But in the mean time you can get the HEX for each chimera color here:

https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/colortables.html

And convert to RGB here:

http://hex.colorrrs.com

You also have to divide by 255 :)

**Comment by shruthivis** [comment]
Thanks! Meanwhile Chimera fixed the issue from their end, and will now
allow selection of multiple copies at the same level (available from
tomorrow's build onwards).
