### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#2]
extend documentation

**Comment by cgreenberg** [comment]
We should start using doxygen. Can follow the example of IMP.Parallel. It's pretty straightforward. Only question: does it go on the IMP website? Somewhere new?

**Comment by benmwebb** [comment]
Right now it won't go anywhere, since it's not part of IMP. The best long term option IMHO is to incorporate pmi into IMP proper. You can either roll the pmi repo into IMP itself, or you could add pmi as an IMP submodule (just as is currently done for RMF). Both have pros and cons.

**Comment by Pellarin** [comment]
Is it possible to have doxygen pages within github?

**Comment by benmwebb** [comment]
It's possible to put the doxygen HTML files anywhere you like. But you'd have to set up all the infrastructure. Much easier just to use that already in IMP.

**Comment by benmwebb** [comment]
PMI docs should show up as part of the main IMP docs these days.
