### ISSUE TITLE
IMP.pmi.tools.get_terminal_residue() does not return BEAD as a C-terminus

### ISSUE THREAD

**Issue by procyon777** [salilab/pmi#206]
Currently IMP.pmi.tools.get_terminal_residue() returns a terminal particle ONLY at a SPECIFIC residue level.  By default setting (resolution = 1), it does not return any large BEAD at its actual C-terminus.

For example, I have a protein that has a template structure available only in the middle region, so this function returns a resolution 1 particle at the end of the PDB covered region, not the actual BEAD (resolution 10) at C-terminus.

Of course I can change the input parameter per each protein, but it is very painful for a large system.  Would it be possible to select a residue (including BEAD) at its closest input resolution?  Even when resolution = 1, it should return BEAD (resolution 10) at the C-terminus, since it is the last residue at the closest input resolution.

Many Thanks!

**Comment by Pellarin** [comment]
Please push a test function that reproduces the issue

**Comment by Pellarin** [comment]
The function works as expected. I commited a test function and better documented the function here fa5d4b0968011d4d4b9a2a1e0b3691897a200565

To get the termini you have to use:

```
residues=IMP.pmi.tools.select_by_tuple(representation,molecule_name,resolution)
nterminal=residues[0]
cterminal=residues[-1]
```

**Comment by procyon777** [comment]
Thanks a lot!  It works well by following what you suggested.
