### ISSUE TITLE
Collective GMM representations for multiple molecules

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#209]
At least in PMI1 (BuildModel1 macro) it would be helpful for the NPC and other complexes if you could represent a group of molecules with a single GMM. In the NPC we like to represent the entire Nup84 sub- complex, which is kept rigid (including "flexible beads" since they're already optimized) with one GMM. Of course this might be a nice feature in PMI2 as well.

The problem is the way GMMs are stored hierarchically. In PMI1 they are in a child of the molecule hierarchy. We could just hack this by partitioning the GMM storage based on nearest neighbors or something - it shouldn't matter as long as the whole thing is rigid. In PMI2, GMMs are stored as density representations...we could do the same partition there as well. It's kind of a hack though.

Thoughts, @Pellarin

**Comment by Pellarin** [comment]
Yes... maybe we can introduce an index in the build macro table, similar to
what we have for the rigid body and super rigid body.
Domains that have the same index are approximated by the same GMM...

# Riccardo Pellarin, PhD

Institut Pasteur
CNRS UMR 3528
25, rue du Docteur Roux
75724 Paris Cedex 15, France
riccardo.pellarin@pasteur.fr
+33 (0)1 44 38 93 63

On Sat, Jun 11, 2016 at 1:16 AM, Charles Greenberg <notifications@github.com
