### ISSUE TITLE
Conform to PEP8 style guidelines

### ISSUE THREAD

**Issue by sethaxen** [salilab/pmi#212]
Currently, most PMI files do not conform to Python's [PEP8 style guidelines](https://www.python.org/dev/peps/pep-0008/). This may be fixed with no change to functionality, and it should improve readability of the code. Especial attention should be paid to order of imports and use of whitespace.

**Comment by benmwebb** [comment]
Are you sure that's the case? The cleanup scripts are supposed to enforce PEP8, just as they do for IMP. This should also be checked for by the git pre-commit hook (although we have no way to force people to use that of course). If there really is non-PEP8 code in the repo, running `cleanup_code.py` should fix it.

**Comment by sethaxen** [comment]
It doesn't appear to be working for everything. For example, `BiStableDistanceRestraint` in `IMP.pmi.restraints.basic` breaks a number of PEP8 rules regarding whitespace (there should be whitespace around equal signs when operators are declared, there should be a space after commas in the list of arguments passed to a method). Running `cleanup_code.py` did not change this. Additionally, a number of lines unnecessarily exceed 79 characters. Most of the files in PMI have similar violations.

**Comment by benmwebb** [comment]
Oh, OK, you are more strict than I am! The default checks use `reindent.py`, which checks a subset of PEP8 (indentation, extra whitespace, etc.) You can have cleanup_code.py use `autopep8` to more aggressively correct PEP8 violations, but it tends to make more of a mess of the file.

Personally, if I had to choose between documenting/testing the code and making it PEP8 compliant, I'd choose the former. To take your example, `BiStableDistanceRestraint` is poorly documented and not tested at all.

**Comment by sethaxen** [comment]
But do we have to choose? And, is there an easy way to see all classes/methods that are currently untested?

**Comment by benmwebb** [comment]
> But do we have to choose?

Of course you can do both if you have the time. But I don't.

> easy way to see all classes/methods that are currently untested?

Look at the Python coverage links on the [nightly build page](https://integrativemodeling.org/nightly/results/). For example, [today's PMI coverage](https://integrativemodeling.org/nightly/logs/develop/20161004/coverage/python/pmi/lib_IMP_pmi_restraints_basic_py.html) clearly shows that `BiStableDistanceRestraint` is not covered (red or yellow lines).

**Comment by sethaxen** [comment]
> Of course you can do both if you have the time. But I don't.

That's why I self-assigned it. I'll just pick away at it slowly. :-)

> Look at the Python coverage links on the nightly build page. For example, today's PMI coverage clearly shows that BiStableDistanceRestraint is not covered (red or yellow lines).

Very useful, thanks!

**Comment by benmwebb** [comment]
`flake8` has been run on the code base and should be run as part of CI, so everything should now be PEP8 compliant and should stay that way.
