### ISSUE TITLE
Merge ExternalBarrier and DistanceToPointRestraint restraints

### ISSUE THREAD

**Issue by sethaxen** [salilab/pmi#215]
Internally, `ExternalBarrier` and `DistanceToPointRestraint` in `IMP.pmi.restraints.basic` do the same thing: both use a harmonic upper bound to restraint particles to a provided point. The only differences between them lie in how the particles are selected from the representation/hierarchies, the resolution upon which they act, and whether the restraint kappa is tunable. They should be merged into one restraint.

**Comment by procyon777** [comment]
Sorry, would you please keep these two restraints untouched, at least for few months until I finish my projects?  I'm seriously worrying if anything breaks down by changing these.

**Comment by sethaxen** [comment]
@procyon777, I'd really like to continue cleaning up and modernizing the restraints, ensuring everything passes the tests. @benmwebb, should we create a new branch using the new PMI restraint base so I can continue down that route?

**Comment by benmwebb** [comment]
Sure, do it as before - fork, branch and then submit a pull request with your changes.

**Comment by procyon777** [comment]
Many Thanks

**Comment by sethaxen** [comment]
@benmwebb last time I just branched and then submitted a pull request. Do I need to fork?

**Comment by benmwebb** [comment]
I think forking is cleaner but it's your call. Just remember to delete the temporary branch once it gets merged in.
