### ISSUE TITLE
Port all systems to PMI2

### ISSUE THREAD

**Issue by benmwebb** [salilab/pmi#216]
We should port each of the [IMP systems](https://integrativemodeling.org/systems/) to PMI2. This should ensure that these systems continue to work in the future, expose any areas where PMI2 is lacking relative to PMI1, and allow us to promote PMI2 as the default PMI.

For each system this requires the following steps:
1. Create a `develop` branch in the GitHub repository (the `master` branch is required to work with the last IMP stable release) and make any necessary changes there.
2. Change scripts to use PMI2.
3. Verify that the system behaves qualitatively the same as the old PMI1 system (one would assume very similar or identical representations, restraints and movers are set up, although the final models will doubtless be different).
4. If something isn't right, fix PMI2 as necessary and add test cases to make sure it stays fixed.
5. Once all the systems work, we'll make a new IMP release that incorporates all the needed changes, at which point I'll merge the changes back into the system's `master` branch.

@saltzberg has already volunteered to handle the [IMP tutorial](https://github.com/salilab/imp_tutorial/). I'll handle the [glycophorin](https://github.com/integrativemodeling/glycophorin) and [integrin](https://github.com/integrativemodeling/integrin) example systems to start with, before moving on to "real" systems.

**Comment by procyon777** [comment]
Sorry, I'm serious worrying that PMI2 may break many things that I have been working under PMI1 for my big projects.  Is it possible to leave PMI1 untouched?  I may not have enough time to convert my projects and test every single change.

**Comment by procyon777** [comment]
I misunderstood what you suggested, and I deleted my previous comment.  Sorry about it

**Comment by saltzberg** [comment]
I'll work on other systems that I'm familiar with, namely the [mediator](https://github.com/integrativemodeling/mediator), [exosome](https://github.com/integrativemodeling/exosome) and [phoq](https://github.com/integrativemodeling/phoq).

**Comment by benmwebb** [comment]
Since I'm not that familiar with PMI2, I added a wiki page cheat sheet for [transitioning from PMI1 to PMI2](https://github.com/salilab/pmi/wiki/PMI1-to-PMI2-transition-guide). Please take a look at that wiki page and make corrections where necessary and add more notes. This will eventually go into the manual to help others transition to PMI2.

Obviously there won't always be a 1:1 mapping between PMI1 and PMI2 methods. Where this isn't the case, a note pointing to the new PMI2 way of doing things would be helpful.

**Comment by Pellarin** [comment]
We should follow the imp_tutorial/develop example as much as possible

**Comment by benmwebb** [comment]
Note that realistically it will take a long time to transition published applications to PMI2, and there's little benefit to doing so. salilab/imp#997 may be a better solution. We should definitely transition examples and tutorials though.

**Comment by benmwebb** [comment]
> We should follow the imp_tutorial/develop example as much as possible

This would require the development version of the tutorial to work, which isn't yet the case. See [the latest Travis failures](https://travis-ci.org/salilab/imp_tutorial/builds/303673203).

**Comment by benmwebb** [comment]
All tutorials and examples should now use PMI2. Legacy systems will continue to use PMI1, although new applications use PMI2.
