### ISSUE TITLE
Connectivity for disordered proteins

### ISSUE THREAD

**Issue by shruthivis** [salilab/pmi#217]
According to IMP.pmi.restraints.stereochemistry.ConnectivityRestraint, when the protein is disordered, this formula is used for the distance between consecutive beads:
optdist= sqrt(5/3)_1.93_[number_of_residues_in_first_bead/2 + number_of_residues_in_last_bead/2 + number_of_residues_in_gap]^0.6
Based on random coil length in [Kohn PNAS 2004](http://www.pnas.org/content/101/34/12491.abstract). Since it is an estimate of the radius of the sphere derived from the radius of gyration predicted from the random coil length, shouldn't the actual distance be twice the radius? i.e. 2*optdist?

**Comment by benmwebb** [comment]
Kohn's paper states R<sub>G</sub> = R<sub>0</sub>N<sup>v</sup> with R<sub>0</sub> = 1.330 and v = 0.598.

The formula in IMP looks like it uses R<sub>0</sub> = sqrt(5/3)1.93. Not sure where that comes from but numerically that's 2.49, which is roughly twice the value from Kohn's work. So I think your factor of two is already included. Looks like @saltzberg wrote that code though, so he would know for sure.

**Comment by saltzberg** [comment]
The restraint is formulated correctly as intended.  There is a correction in the paper that changes R0 to 1.93 and sqrt(5/3) is the scaling factor between the radius of gyration and the radius of a sphere.

Now, this of course assumes a sphere, for which disordered coil is almost certainly not.  I'm all for exploring a different formulation for this if there are any ideas.

@shruthivis, did you notice any modeling that was not working as expected?

**Comment by shruthivis** [comment]
I now understand how that formula comes about and forgot to close this
issue. Thanks!
