### ISSUE TITLE
add develop branch

### ISSUE THREAD

**Issue by yannickspill** [salilab/pmi#22]
when I type `git imp update` in the IMP source tree, I always get problems updating pmi because it doesn't have a develop branch. I propose we duplicate the master branch to create a develop branch, and only work on that one.

**Comment by Pellarin** [comment]
What issues do you see? It should work, it always worked with me and everybody else. If it doesn't it is an issue of how the submodules are managed by imp.

**Comment by yannickspill** [comment]
it would complain about the module not being set up properly. I don't have an error message right now.

**Comment by yannickspill** [comment]
that being said maybe the recent changes to setup_git.py helped with that because I don't recall seeing such a message this morning.

**Comment by Pellarin** [comment]
Yes, there are a lot of modules using git-master, pmi is not the only one. Therefore let's keep it under master. Let me know if you see weird things.

**Comment by drussel** [comment]
That should like you may have been trying to set up git imp flow in pmi
(perhaps automatically by running setup_imp.py), which is not something
that is support by every module.

**Comment by yannickspill** [comment]
oh that's probably it.

**Comment by Pellarin** [comment]
What should I do, then?

**Comment by drussel** [comment]
Ignore it :-)

On Mon, Feb 10, 2014 at 2:19 PM, Riccardo Pellarin <notifications@github.com

> wrote:
> 
> What should I do, then?
> 
> Sent from my iPhone
>
