### ISSUE TITLE
Why is SerialMover used?

### ISSUE THREAD

**Issue by sethaxen** [salilab/pmi#229]
Perhaps I'm wrong, but it looks like `IMP.core.SerialMover` is used in `IMP.pmi.samplers.MonteCarlo` to propose movers in order, one for each Monte Carlo step. My understanding is that this mover is only recommended when using an incremental scoring function.

**Comment by Pellarin** [comment]
SerialMover enables a Gibbs Sampling scheme, where particles (ie, XYZ, RigidBodies, Scales) are all moved once. Nowhere is strictly recommending this mover with incremental scoring function, or at least I don't quite understand your question.

**Comment by shruthivis** [comment]
Agree with Riccardo, given a list of movers (eg. individual bead
movers,rigid body movers..)  it enables performing an MC step once per
mover in the order specified in the list (Gibbs sampling essentially).  The
SerialMover only specifies how the Gibbs sampling is done and doesn't
impose any requirements on the scoring function.


On Fri, Mar 17, 2017 at 3:50 AM, Riccardo Pellarin <notifications@github.com

**Comment by Pellarin** [comment]
Should we close this?

**Comment by sethaxen** [comment]
Yes, thanks, you guys are absolutely right.
