### ISSUE TITLE
representation.add_component_density keyword argument "resolution" is used also in IMP.em.SampledDensityMap

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#23]
In representation.add_component_density dmap=IMP.em.SampledDensityMap(fragment_particles,resolution,voxel_size)
will throw an exception (only running with IMP usage exception on) when resolution=0.0
However, the resolution for   IMP.em.SampledDensityMap should be different from the resolution argument passed to representation.add_component_density

**Comment by Pellarin** [comment]
It throws:

```
autobuild_model: constructing Nup84 from pdb data/ScNup84N_7-488.pdb and chain A
autobuild_model: constructing fragment (1, 6) as a bead
autobuild_model: constructing fragment (7, 488) from pdb
autobuild_model: constructing Nup84 from pdb data/ScNup84C_506-726.pdb and chain A
autobuild_model: constructing fragment (489, 505) as a bead
autobuild_model: constructing fragment (506, 726) from pdb
add_component_density: will multiply by mass 51551.3516
add_component_density: sampling points
Traceback (most recent call last):
  File "nup84.modeling.rex.py", line 30, in <module>
    execfile("nup84.topology.py")
  File "nup84.topology.py", line 46, in <module>
    outputmap='data/Nup84_1_dens.mrc') # do the calculation and output the mrc
  File "/cello1/home/etjioe/Salilab/Project/IMP/install3/imp-20140210-pmi-isd2-fast/lib/IMP/pmi/representation.py", line 541, in add_component_density
    dmap=IMP.em.SampledDensityMap(fragment_particles,resolution,voxel_size)
  File "/cello1/home/etjioe/Salilab/Project/IMP/install3/imp-20140210-pmi-isd2-fast/lib/IMP/em/__init__.py", line 1447, in __init__
    this = _IMP_em.new_SampledDensityMap(*args)
_IMP_base.UsageException: Usage check failure: inv_rsigsq out of range
```

**Comment by Pellarin** [comment]
You get the error if run as IMP Release.

**Comment by cgreenberg** [comment]
Did you verify that fragment_particles is non-empty, and that the particles are decorated as XYZ and Mass? I suspect that they are missing Mass. It's required to create a sampled density map.

**Comment by Pellarin** [comment]
they should be assigned correctly. Why you pass resolution to IMP.em.SampledDensityMap?

**Comment by cgreenberg** [comment]
Ah. I see. I made a mistake. The resolution passed to SampledDensityMap is for the intermediate map sampling, probably we should just always make it 1. But probably we need something that more accurately simulates the actual electron density.
