### ISSUE TITLE
ProcessOutput is slow; don't use eval()

### ISSUE THREAD

**Issue by saltzberg** [salilab/pmi#230]
Reading stat files using eval() is very slow.  Rewriting this with standard string parsers should speed this up by a fewfold.

**Comment by benmwebb** [comment]
It's also horribly insecure, since an evil person could put arbitrary Python code in a stat file.

**Comment by benmwebb** [comment]
This should be more secure since we use `ast.literal_eval` instead of plain `eval` now. Long term, stats should be stored in the RMF file anyway.
