### ISSUE TITLE
Don't call Model.update() from restraint get_output() methods

### ISSUE THREAD

**Issue by sethaxen** [salilab/pmi#239]
Most (if not all) restraints call `IMP.Model.update()` at the beginning of their `get_output()` methods. Consequently, the outputting process repeatedly updates the model unnecessarily (see [here](https://github.com/salilab/pmi/blob/develop/pyext/src/output.py#L738-L751)). For systems where the scoring function itself is inexpensive, these redundant calls can dominate the runtime. It seems it would be better if either `IMP.pmi.output.Output` updated the model once before getting outputs or if it assumed that the model was updated, leaving it to the method that triggers saving of outputs (e.g. `IMP.pmi.macros.ReplicaExchange0`) to update the model once before outputting.

Do the PMI architects see any fatal flaws here?

**Comment by Pellarin** [comment]
It is ok with me
