### ISSUE TITLE
Cmake and pmi examples

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#24]
I get this error with cmake on the cluster:

CMake Error: CMake can not determine linker language for target:IMP.pmi-glycophorin.modelin.py
CMake Error: CMake can not determine linker language for target:IMP.pmi-integrin.modeling.py

Something wrong with the files in the examples directory?

**Comment by Pellarin** [comment]
I don't really know how an example should look like...

**Comment by Pellarin** [comment]
I have to write 

#!/usr/bin/env python

at the beginning...

**Comment by Pellarin** [comment]
Tried but yet the same error

**Comment by Pellarin** [comment]
Charles spotted it out: 

glycophorin.modelin.py -> glycophorin_modelin.py

no dot, otherwise CMake doesn't get the extension.

**Comment by drussel** [comment]
Yeah. A bit dumb on cmake's part. I'll change the script so that it supports extra crap before the .py
