### ISSUE TITLE
Make a PMI1-only module

### ISSUE THREAD

**Issue by benmwebb** [salilab/pmi#241]
Branch the repository and remove all PMI2 functionality; then import this branch into IMP as `IMP.pmi1`. Keep this around so that existing published systems still work.

Have this module print a huge warning message on import to the effect that it's only present to support legacy published applications, and won't be updated or supported, so shouldn't be used for new stuff. Point users to IMP.pmi (PMI2) instead. Relates salilab/imp#997.

**Comment by sethaxen** [comment]
What's the timeline for this? Is it intended to be in the 2.9.0 release or the next one?

**Comment by benmwebb** [comment]
Next one. I've already branched for 2.9.0 - no new features.

**Comment by benmwebb** [comment]
This is maintained now in the `legacy-pmi1` branch.
