### ISSUE TITLE
Gaussians instead of beads?

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#40]

**Comment by cgreenberg** [comment]
Could be better than simplifying along backbone. Also we can use a gaussian excluded volume restraint.

**Comment by Pellarin** [comment]
Mmmmh the idea was interesting, did we try?

**Comment by cgreenberg** [comment]
Gaussians would be a probabilistic representation of residue positions. Could be interesting - kind of a generalization of using the "sigma" term in the crosslink restraint. Unclear how to make this work for general restraints.
