### ISSUE TITLE
Add into IMP as a submodule

### ISSUE THREAD

**Issue by benmwebb** [salilab/pmi#47]
I'd like to add pmi to IMP proper. Since you guys seem happy enough hacking away in the pmi repository, I suggest adding it as a submodule (just like we currently do for RMF). Then nothing would need to change in pmi - we'd just need to update the submodule reference in IMP periodically to get the latest pmi (submodules point to a specific revision of a repository - they don't track HEAD automatically).

This would
- "magically" build your documentation and make it available as part of the IMP docs (see issue #2).
- mean that users wouldn't have to check out pmi separately to build it
- put pmi in the binary installers so people can try it out without having to compile IMP (nice for Windows users!)

Since pmi is still in heavy development, I suggest waiting until after the IMP 2.2 release to do this.

Comments?

**Comment by Pellarin** [comment]
Sounds good for me!

**Comment by cgreenberg** [comment]
Agreed, it'd be awesome to get it documented.
