### ISSUE TITLE
Restraints should complain if you pass them a resolution that hasn't been set up.

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#53]

**Comment by Pellarin** [comment]
No, PMI works in the way that it picks the closest resolution. It is all
about this concept: you still want to apply a restraint also to low
resolution pieces.

**Comment by cgreenberg** [comment]
OH cool. That would be a nice thing to include in the eventual PMI.Restraint base class

**Comment by Pellarin** [comment]
Yes
