### ISSUE TITLE
Beads and corresponding densities, when constrained within the same rigid body, they drift away from each other

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#55]
This is strange, because apparently not happening in every system environment. Still investigating.

**Comment by cgreenberg** [comment]
Maybe we need to set_coordinates_are_optimized for the gaussians?

**Comment by Pellarin** [comment]
No, they both move, is not that one of them is fixed. I guess it is related to the NonRigidMember in a RigidBody
