### ISSUE TITLE
Name change to IMP.factory?

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#61]
There's been some discussion to change the name, and since we are preparing a paper on the module, now might be a good time. I like IMP.factory a lot, since it describes in one word what the module does: create IMP things. Whereas "python modeling interface" could mean anything, really.

Not sure how hard it would be to change everything in the code, git, etc....

**Comment by benmwebb** [comment]
Changing the name in the code isn't a huge deal - it's just a problem for people that go looking for PMI and then can't find it.

My vote is to call it "IMP". Semi serious here, a lot of parts of PMI should probably be distributed throughout IMP proper. But for the subset of functionality of setting up "things", IMP.factory makes sense.

**Comment by cgreenberg** [comment]
Well I like that it's separate since we're selling it as a package of standard procedures in structure modeling (whereas IMP as a whole can be used, basically, for anything). Anyway, it seems the major barrier to changing the name is that publications with the name PMI are already in the works...
