### ISSUE TITLE
Inconsistent python whitespace

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#62]
In some files the indentations are 3 spaces, others they are 4. I believe that IMP usually uses 4 spaces, can we enforce this everywhere? Isn't this what python autoformat is supposed to do?

**Comment by cgreenberg** [comment]
Note that python says we should be using 4 spaces for each indentation level:

http://legacy.python.org/dev/peps/pep-0008/

**Comment by benmwebb** [comment]
Well, really what should be happening is that PMI should be subject to the same commit-time checks as the rest of IMP (one of which is that it is PEP8 compliant). I'll set that up - then all users need to do is run `setup_git.py`, same as for the rest of IMP.

**Comment by cgreenberg** [comment]
Yes! Exactly.

**Comment by benmwebb** [comment]
OK, in progress. Note that the IMP checks require work is done in the develop branch rather than master. I'll create such a branch so that everything is happy.

**Comment by benmwebb** [comment]
OK, should all be working now as as 6c34972. You'll need to "git checkout develop" to continue.
