### ISSUE TITLE
representation_new.py: Consider making System pickleable

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#67]
It'd be nice to be able to store the representation_new.py's System class (and State and Molecule and Residue) in a pickled file. Would require removing IMP objects from the classes, and rather storing the operations needed to reconstruct the hierarchy from the input PDB files. Could be lightweight, fast, portable, etc.

**Comment by benmwebb** [comment]
Most IMP classes are now pickleable, so in most cases we should also be able to pickle `System` without any special considerations.
