### ISSUE TITLE
Add randomized tests for build()

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#74]
Randomize the resolutions, what's atomic, etc, many times and test!

**Comment by benmwebb** [comment]
I _hate_ that kind of test, for what it's worth. It just means that it'll fail randomly (say 1% of the time). So chances are you'll ignore any failures (even if you try to reproduce them, you won't be able to).

Much better to try and catch all corner cases - coverage can help you here.

**Comment by cgreenberg** [comment]
Yeah I'm just worried about the unknown unknowns. I'd like build() to fail gracefully if the user tries to do something dumb. Maybe we just need to think of possible mistakes the user would make...

**Comment by benmwebb** [comment]
By all means do some one-off fuzz testing... then write tests for each "dumb thing" that fail 100% of the time. Then you might actually fix them. ;)
