### ISSUE TITLE
None of the examples work

### ISSUE THREAD

**Issue by benmwebb** [salilab/pmi#83]
e.g. http://integrativemodeling.org/nightly/results/?comp=115&plat=4

They are unusably slow, require isd_emxl (which is private) or use hard-coded paths for input files (need to wrap these with `IMP.pmi.get_example_path()`)

**Comment by cgreenberg** [comment]
Ouch. I will move the isd_emxl-using examples to that module. Eventually they will be in isd and this won't be a problem.

**Comment by cgreenberg** [comment]
I think this is fixed because there's only two examples and they both work :)

**Comment by benmwebb** [comment]
Well sure, because I worked around it by deleting the broken ones in 8e4f1d3f2.

**Comment by cgreenberg** [comment]
Some are outdated anyway. We're going to slowly add new ones.
