### ISSUE TITLE
Reorganize python src into folders

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#85]
A lot of files have too many classes, it's hard to navigate. If we make things more modular we can also create more tests (yay). Here's my proposed directory structure:

pyext/src/representation/
representation.py (class for building systems)
construction_macros.py (classes that create Representations, including BuildModel0, BuildModel1, ...)
structure_tools.py, sequence_tools.py, hierarchy_tools.py (functions used in representation, could be consolidated)
dof.py (new degrees of freedom class)

pyext/src/sampling/
samplers.py (MC, MD, ...)
sampling_macros.py (macros that call the individual samplers, including ReplicaExchange0 from macros.py)
sampling_tools.py (tools for getting sampling going)

pyext/src/io/
output.py (output class)
input.py (including ProcessOutput class, and a new class to read many rmf and stat files, as is currently done in the AnalysisReplicaExchange0 macro)
data_tools.py (for reading restraint data files)

pyext/src/analysis/
alignment.py  (actually, these utilities should probably go in IMP proper)
clustering.py
crosslinktable.py (maybe we could just include the XL_analysis as a sub-repository?)
plotting.py (including the loose functions from output.py)
model_densities.py (class to create density maps from ensembles, could go in IMP.em)

Also we could start using the bin/ directory to include useful, complete scripts like:
process_output.py
analyze.py (new script to get distances, cluster, and draw output for multiple of REX runs)

**Comment by benmwebb** [comment]
Be careful with `bin/` - stuff in there doesn't get installed and so isn't the place to put "useful" scripts if you want end users to see them. I would put such scripts in as examples (if you can make them runnable in reasonable time) or possibly as Python modules (then run them as `python -m IMP.pmi.my_example_script` or similar).

**Comment by cgreenberg** [comment]
Ben, why aren't things in bin/ installed? That seems kind of weird. If we want standalone scripts that help with analysis, along with lots of input/output options, then it shouldn't exactly be an example.

**Comment by benmwebb** [comment]
Because `bin` is not for applications - that's what the `applications` directory is for (although see salilab/imp#750).
