### ISSUE TITLE
Add a class for problem setup

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#90]
Could replace the dictionary used in autobuild scripts. That way it could be parsed from a text file or just manually set up (lots of add_subunit() functions etc). Advantage is you can do lots of checks. And it could be amenable to slicing (e.g. I only want to model some parts for this simulation). Also downstream analysis could use the same data files. E.g. for labels in plots, or examining subsets of restraints. It could also be helpful in pairing with the crosslinking data files so those could be plotted automatically in a useful way, even before simulations are run.

**Comment by benmwebb** [comment]
+1 from me. I am very wary of overusing dictionaries. They are hard to read and hard to check. And you can't look them up in a help document anywhere. (Contrast with a nice Python shell like IDLE, where you can just mouseover a class name and the docs pop up.)

For a non-PMI example, check out this SOAP script which makes extensive use of heavily nested dictionaries to control its execution:
https://github.com/salilab/SOAP/blob/master/examples/mhc2/select_dist_pot.py

What does it do? What does each parameter control? I have no idea. If you have no idea either, chances are someone who is not familiar with PMI won't understand current PMI scripts either.
