### ISSUE TITLE
Move examples to their own repositories

### ISSUE THREAD

**Issue by benmwebb** [salilab/pmi#94]
The current PMI examples look more like biological systems to me - i.e. long running simulations of "real" systems - as opposed to typical IMP examples, which are used to demonstrate (and test) functionality and run in only a few seconds. They are also really large - the binary installers for IMP 2.3 are more than twice the size as those for IMP 2.2 purely due to including the PMI examples. Since the examples don't work anyway (see issue #83) this is super-wasteful.

I would much rather put each example in its own repository and test them all with the other biological systems (http://integrativemodeling.org/systems/). Of course, the PMI docs can point to these systems as examples of how to use PMI (once issue #83 is fixed!) Any objections?

**Comment by Pellarin** [comment]
Yes, They cannot be accelerated. let's make them biological systems. At least glycophorin and integrin.

**Comment by benmwebb** [comment]
OK, I'll set up the repositories.
