### ISSUE TITLE
Consider using pandas for the stat files

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#97]
Currently it's a slow process to read from lots of them, whereas pandas could read tons of them and filter very quickly. It's easy to implement, I'm just worried about how to handle backwards compatibility...

**Comment by benmwebb** [comment]
Note also that pandas is a very awkward dependency (Fedora doesn't have it; RedHat/CentOS not only don't have it, they don't have a new enough numpy for it either) so making it a requirement for PMI would make it really hard for people to use PMI.

**Comment by Pellarin** [comment]
After Ben suggestion, I prefer not to include Pandas dependency.
